#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
output_file="${repo_root}/ADVERTISING.md"

html_escape() {
  sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

run_cmd() {
  local cmd="$1"
  local output
  output=$(eval "${cmd}" 2>&1 || true)
  printf '%s' "${output}"
}

write_header() {
  cat <<'DOC' > "${output_file}"
# Remote Desktop Access

Use the RDP file below to connect to the Windows host from a compatible client.

- Windows Host RDP: [docs/windows-host.rdp](docs/windows-host.rdp)

# System Advertising

Generated by `scripts/diagnostics/update-advertising.sh`. Outputs are verbatim from the commands below.
DOC
}

write_table_header() {
  cat <<'DOC' >> "${output_file}"
| 🧩 Item | 🧰 Command | 📄 Output |
| --- | --- | --- |
DOC
}

add_row() {
  local item="$1"
  local cmd="$2"
  local output="$3"
  local escaped
  escaped=$(printf '%s' "${output}" | html_escape)
  printf '| %s | `%s` | <pre>%s</pre> |\n' "${item}" "${cmd}" "${escaped}" >> "${output_file}"
}

write_header

cat <<'DOC' >> "${output_file}"

## 🧭 Hostnames

DOC
write_table_header
add_row "💻 WSL hostname" "hostname" "$(run_cmd "hostname")"
add_row "🪟 Windows hostname" "cmd.exe /c hostname" "$(run_cmd "cmd.exe /c hostname")"

cat <<'DOC' >> "${output_file}"

## 🧱 Versions

DOC
write_table_header
add_row "🧾 OS release" "lsb_release -a" "$(run_cmd "lsb_release -a")"
add_row "🐧 Kernel" "uname -a" "$(run_cmd "uname -a")"
add_row "🧩 WSL status" "wsl.exe --status" "$(run_cmd "wsl.exe --status")"
add_row "🌱 Git" "git --version" "$(run_cmd "git --version")"
add_row "🐙 GitHub CLI" "gh --version" "$(run_cmd "gh --version")"

cat <<'DOC' >> "${output_file}"

## 🩺 Diagnostics

DOC
write_table_header
add_row "📜 /proc/version" "cat /proc/version" "$(run_cmd "cat /proc/version")"
add_row "📡 resolv.conf" "cat /etc/resolv.conf" "$(run_cmd "cat /etc/resolv.conf")"
